# Generated by Django 4.1 on 2024-01-14 23:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("images", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="thumbnail",
            field=models.ImageField(default=2, editable=False, upload_to="thumbnails/"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="image",
            name="image",
            field=models.ImageField(upload_to="uploads/"),
        ),
    ]
