# Generated by Django 4.1 on 2024-01-14 23:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("images", "0002_image_thumbnail_alter_image_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="thumbnail",
            field=models.ImageField(
                default="thumbnails/default.png", upload_to="thumbnails/"
            ),
        ),
    ]
