# Generated by Django 4.1 on 2024-01-14 23:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("images", "0003_alter_image_thumbnail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="thumbnail",
            field=models.ImageField(
                default="/thumbnails/default.png", upload_to="thumbnails/"
            ),
        ),
    ]
